server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: shopping-service
          uri: lb://shoping-service
          predicates:
            - Path=/invoices/**
  sleuth:
    enabled: true
    sampler:
        probability: 1.0
    trace-id128: true
            
            